// frontend-react/src/pages/Login.jsx
import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { BookOpen, LogIn, Lock, Mail, UserPlus } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';

export default function Login() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setErrorMessage('');

    let cleanEmail = (email || '').trim().toLowerCase();
    if (cleanEmail === 'student') cleanEmail = 'student@slms.com';
    if (cleanEmail === 'faculty') cleanEmail = 'faculty@slms.com';
    if (cleanEmail === 'admin') cleanEmail = 'admin@slms.com';
    if (cleanEmail === 'librarian') cleanEmail = 'librarian@slms.com';

    if (cleanEmail === 'admin@slms.com' || cleanEmail === 'librarian@slms.com') {
      setLoading(false);
      setErrorMessage('Invalid email or password. Please check your credentials.');
      return;
    }

    const res = await login(cleanEmail, password);
    setLoading(false);

    if (res.success) {
      const userRole = res.user?.role || '';
      if (userRole === 'super_admin' || userRole === 'admin' || userRole === 'librarian' || userRole.includes('admin')) {
        localStorage.removeItem('slms_token');
        localStorage.removeItem('slms_user');
        setErrorMessage('Invalid email or password. Please check your credentials.');
        return;
      }
      navigate('/');
    } else {
      setErrorMessage(res.message || 'Invalid email or password. Please check your credentials.');
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-slate-950 p-4 relative overflow-hidden">
      {/* Background Glows */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-indigo-600/20 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-violet-600/20 rounded-full blur-3xl pointer-events-none" />

      <div className="w-full max-w-md bg-slate-900/90 backdrop-blur-xl border border-slate-800 rounded-3xl p-8 shadow-2xl space-y-6 relative z-10">
        <div className="text-center space-y-2">
          <div className="w-14 h-14 rounded-2xl bg-gradient-to-tr from-indigo-600 to-violet-500 flex items-center justify-center text-white mx-auto shadow-lg shadow-indigo-500/30">
            <BookOpen className="w-7 h-7" />
          </div>
          <h1 className="text-2xl font-bold text-white tracking-tight">Smart Library System</h1>
          <p className="text-xs text-slate-400">Enter your credentials to access your portal</p>
        </div>

        {errorMessage && (
          <div className="p-3.5 bg-rose-500/10 border border-rose-500/30 rounded-2xl text-rose-400 text-xs font-semibold">
            {errorMessage}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="text-xs font-semibold text-slate-300 block mb-1">Email Address</label>
            <div className="relative">
              <Mail className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-500" />
              <input
                type="text"
                required
                autoCapitalize="none"
                autoCorrect="off"
                spellCheck="false"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="w-full pl-10 pr-4 py-2.5 text-xs bg-slate-800/80 border border-slate-700 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
                placeholder="you@domain.com"
              />
            </div>
          </div>

          <div>
            <label className="text-xs font-semibold text-slate-300 block mb-1">Password</label>
            <div className="relative">
              <Lock className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-500" />
              <input
                type="password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full pl-10 pr-4 py-2.5 text-xs bg-slate-800/80 border border-slate-700 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
                placeholder="••••••••"
              />
            </div>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-3 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white font-semibold text-xs shadow-lg shadow-indigo-600/30 transition-all flex items-center justify-center gap-2 cursor-pointer"
          >
            <LogIn className="w-4 h-4" /> {loading ? 'Authenticating...' : 'Sign In'}
          </button>
        </form>

        <div className="pt-4 border-t border-slate-800 flex items-center justify-center gap-1.5 text-xs text-slate-400">
          <span>Don't have an account?</span>
          <Link to="/register" className="text-indigo-400 hover:text-indigo-300 font-semibold flex items-center gap-1">
            <UserPlus className="w-3.5 h-3.5" /> Sign Up Free
          </Link>
        </div>
      </div>
    </div>
  );
}

// admin-angular/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AdminApiService } from '../../services/admin-api.service';

@Component({
  selector: 'app-admin-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="min-h-screen flex items-center justify-center bg-slate-950 p-4 relative overflow-hidden">
      <!-- Glow Backgrounds -->
      <div class="absolute top-1/4 left-1/4 w-96 h-96 bg-cyan-600/20 rounded-full blur-3xl pointer-events-none"></div>
      <div class="absolute bottom-1/4 right-1/4 w-96 h-96 bg-blue-600/20 rounded-full blur-3xl pointer-events-none"></div>

      <div class="w-full max-w-md bg-slate-900/90 backdrop-blur-xl border border-slate-800 rounded-3xl p-8 shadow-2xl space-y-6 relative z-10">
        <div class="text-center space-y-2">
          <div class="w-14 h-14 rounded-2xl bg-gradient-to-tr from-cyan-600 to-blue-500 flex items-center justify-center text-white mx-auto shadow-lg shadow-cyan-500/30">
            <svg class="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"/></svg>
          </div>
          <h1 class="text-2xl font-bold text-white tracking-tight">SLMS Admin Console</h1>
          <p class="text-xs text-slate-400">Sign in with administrative credentials to access management console</p>
        </div>

        <div *ngIf="errorMessage" class="p-3.5 bg-rose-500/10 border border-rose-500/30 rounded-2xl text-rose-400 text-xs font-semibold">
          {{ errorMessage }}
        </div>

        <form (ngSubmit)="onLogin()" class="space-y-4">
          <div>
            <label class="text-xs font-semibold text-slate-300 block mb-1">Admin Email Address</label>
            <div class="relative">
              <input
                type="text"
                required
                [(ngModel)]="email"
                name="email"
                placeholder="admin&#64;company.com"
                class="w-full px-4 py-2.5 text-xs bg-slate-800/80 border border-slate-700 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
              />
            </div>
          </div>

          <div>
            <label class="text-xs font-semibold text-slate-300 block mb-1">Password</label>
            <div class="relative">
              <input
                type="password"
                required
                [(ngModel)]="password"
                name="password"
                placeholder="••••••••"
                class="w-full px-4 py-2.5 text-xs bg-slate-800/80 border border-slate-700 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
              />
            </div>
          </div>

          <button
            type="submit"
            [disabled]="loading"
            class="w-full py-3 rounded-xl bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white font-semibold text-xs shadow-lg shadow-cyan-600/30 transition-all cursor-pointer"
          >
            {{ loading ? 'Authenticating...' : 'Sign In to Admin Console' }}
          </button>
        </form>
      </div>
    </div>
  `
})
export class LoginComponent {
  email = '';
  password = '';
  loading = false;
  errorMessage = '';

  constructor(private api: AdminApiService, private router: Router) {}

  onLogin() {
    this.errorMessage = '';
    let cleanEmail = (this.email || '').trim().toLowerCase();
    const cleanPassword = (this.password || '').trim();

    if (cleanEmail === 'admin') cleanEmail = 'admin@slms.com';
    if (cleanEmail === 'librarian') cleanEmail = 'librarian@slms.com';

    if (!cleanEmail || !cleanPassword) {
      this.errorMessage = 'Please enter both Admin Email and Password.';
      return;
    }

    this.loading = true;
    this.api.login(cleanEmail, cleanPassword).subscribe({
      next: (res: any) => {
        this.loading = false;
        if (res.success && res.data?.token) {
          const userRole = res.data.user?.role;
          if (userRole !== 'super_admin' && userRole !== 'admin' && userRole !== 'librarian' && !userRole.includes('admin')) {
            this.errorMessage = 'Access denied. Only Librarians and Admins can access this console.';
            return;
          }
          localStorage.setItem('slms_token', res.data.token);
          localStorage.setItem('slms_user', JSON.stringify(res.data.user));
          this.router.navigate(['/']);
        } else {
          this.errorMessage = res.message || 'Invalid email or password.';
        }
      },
      error: (err) => {
        this.loading = false;
        this.errorMessage = err.error?.message || 'Invalid admin credentials.';
      }
    });
  }
}
